001_000_small_001.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 13
    subtaskId: 0

002_000_small_002.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 13
    subtaskId: 0

003_000_small_003.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 13
    subtaskId: 0

004_000_small_004.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 13
    subtaskId: 0

005_001_square_rand_001.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 21
    subtaskId: 1

006_001_square_rand_002.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 21
    subtaskId: 1

007_001_square_rand_003.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 21
    subtaskId: 1

008_001_square_rand_004.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 21
    subtaskId: 1

009_001_square_rand_005.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 21
    subtaskId: 1

010_001_square_rand_006.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 21
    subtaskId: 1

011_001_square_rand_007.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 21
    subtaskId: 1

012_001_square_rand_008.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 21
    subtaskId: 1

013_002_spec_chain_001.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 12
    subtaskId: 2

014_002_spec_chain_002.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 12
    subtaskId: 2

015_002_spec_chain_003.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 12
    subtaskId: 2

016_002_spec_chain_004.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 12
    subtaskId: 2

017_002_spec_chain_005.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 12
    subtaskId: 2

018_002_spec_chain_006.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 12
    subtaskId: 2

019_003_spec_star_001.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 12
    subtaskId: 3

020_003_spec_star_002.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 12
    subtaskId: 3

021_003_spec_star_003.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 12
    subtaskId: 3

022_003_spec_star_004.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 12
    subtaskId: 3

023_003_spec_star_005.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 12
    subtaskId: 3

024_003_spec_star_006.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 12
    subtaskId: 3

025_003_spec_star_007.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 12
    subtaskId: 3

026_004_big_rand_001.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

027_004_big_rand_002.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

028_004_big_rand_003.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

029_004_big_rand_004.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

030_004_big_rand_005.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

031_004_big_rand_006.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

032_004_big_rand_007.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

033_004_big_rand_008.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

034_004_big_rand_009.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

035_004_big_rand_010.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

036_004_big_rand_011.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

037_004_big_rand_012.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

038_004_big_rand_013.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

039_004_big_rand_014.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

040_004_big_rand_015.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

041_004_big_star_like_001.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

042_004_big_star_like_002.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

043_004_big_star_like_003.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

044_004_big_star_like_004.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

045_004_big_star_like_005.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

046_004_big_chain_like_001.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

047_004_big_chain_like_002.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

048_004_big_chain_like_003.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

049_004_big_chain_like_004.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

050_004_big_chain_like_005.in:
    timeLimit: 2000
    memoryLimit: 262144
    score: 42
    subtaskId: 4

